/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./index.html", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#edf4ff",
        surface: "#f7f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container": "#e7eff9",
        error: "#ba1a1a",
        "surface-variant": "#dbe3ee",
        "primary-fixed": "#dae2ff",
        "surface-dim": "#d3dbe5",
        primary: "#004abb",
        "inverse-surface": "#293139",
        "on-surface": "#141c24",
        "on-tertiary": "#ffffff",
        "inverse-primary": "#b2c5ff",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "on-tertiary-fixed-variant": "#404850",
        "on-tertiary-container": "#e4ecf7",
        secondary: "#355e9e",
        "primary-container": "#0060ee",
        "tertiary-container": "#636b74",
        outline: "#737687",
        "outline-variant": "#c2c6d8",
        "tertiary-fixed": "#dbe3ee",
        "on-primary-fixed-variant": "#003fa3",
        "on-surface-variant": "#424655",
        "secondary-container": "#93b9ff",
        "secondary-fixed-dim": "#aac7ff",
        "on-secondary-container": "#1b4887",
        "surface-container-highest": "#dbe3ee",
        "inverse-on-surface": "#eaf1fc",
        "surface-bright": "#f7f9ff",
        tertiary: "#4b535c",
        "on-secondary-fixed-variant": "#174684",
        "primary-fixed-dim": "#b2c5ff",
        "on-error-container": "#93000a",
        "on-secondary-fixed": "#001b3e",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#bfc7d2",
        "on-secondary": "#ffffff",
        background: "#f7f9ff",
        "on-background": "#141c24",
        "surface-container-high": "#e1e9f4",
        "secondary-fixed": "#d6e3ff",
        "surface-tint": "#0055d4",
        "on-primary-fixed": "#001849",
        "on-primary-container": "#e8ebff",
        "on-tertiary-fixed": "#141c24",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
